name: CD Process

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-then-send-to-telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn install

      - name: make gradle executable
        run: cd android && chmod +x ./gradlew

      - name: buld apk
        run: cd android && ./gradlew assembleRelease

      - name: deploy to telegram
        run: |
          cd android/app/build/outputs/apk/release/
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F text='App Release' ${{secrets.TG_BOT_TOKEN}}/sendMessage
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F document=@app-release.apk ${{secrets.TG_BOT_TOKEN}}/sendDocument
