name: CI Process

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn install

      - name: unit testing
        run: yarn test

  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn install

      - name: check linter
        run: yarn lint
